# .github/workflows/docker-publish.yml

# Nome do workflow que aparecerá no separador "Actions" do seu repositório
name: Build and Publish Docker Image to GHCR

# Define quando este workflow deve ser executado
on:
  # Executa sempre que houver um push para a branch 'main'
  push:
    branches:
      - main
  # Permite que execute este workflow manualmente a partir da interface do GitHub
  workflow_dispatch:

# Define as permissões necessárias para o job
permissions:
  contents: read
  packages: write

jobs:
  # Define um único job chamado 'build-and-push'
  build-and-push:
    # O tipo de máquina onde o job irá correr (Ubuntu mais recente)
    runs-on: ubuntu-latest

    steps:
      # 1. Checkout do Código
      # Baixa o código do seu repositório para a máquina virtual
      - name: Checkout repository
        uses: actions/checkout@v4

      # 2. Login no GitHub Container Registry (ghcr.io)
      # Utiliza um token especial (GITHUB_TOKEN) que o GitHub gera automaticamente para autenticar
      - name: Log in to the Container registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          # GITHUB_ACTOR é o seu nome de utilizador do GitHub
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      # 3. Extrair metadados da imagem (nome e tag)
      # Define o nome da imagem e a tag
      - name: Extract metadata for Docker
        id: meta
        uses: docker/metadata-action@v5
        with:
          # CORREÇÃO: O nome da imagem foi convertido para minúsculas para ser compatível com o Docker.
          images: ghcr.io/clankjake/painel-plex

      # 4. Construir e Enviar a Imagem Docker
      # Utiliza o Dockerfile no seu repositório para construir a imagem e enviá-la para o ghcr.io
      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
